// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {}

interface Link {
  name: string;
  value: string;
}
