// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {}

interface Link {
  hash: string;
  destination: string;
  createdAt: string;
  clicks: number;
  name: string;
}
